"""added job embedding

Revision ID: 32692c34628a
Revises: acf25360d55e
Create Date: 2026-04-25 20:03:47.179063

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32692c34628a'
down_revision: Union[str, Sequence[str], None] = 'acf25360d55e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('required_skills', sa.Text(), nullable=True))
    op.add_column('jobs', sa.Column('embedding', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'embedding')
    op.drop_column('jobs', 'required_skills')
    # ### end Alembic commands ###
