"""create recruiters table

Revision ID: e3aa28d5caf0
Revises: 0e17367dd697
Create Date: 2026-04-24 10:17:09.257617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3aa28d5caf0'
down_revision: Union[str, Sequence[str], None] = '0e17367dd697'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recruiters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recruiters_email'), 'recruiters', ['email'], unique=True)
    op.create_index(op.f('ix_recruiters_id'), 'recruiters', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recruiters_id'), table_name='recruiters')
    op.drop_index(op.f('ix_recruiters_email'), table_name='recruiters')
    op.drop_table('recruiters')
    # ### end Alembic commands ###
